# Generated by Django 5.1.2 on 2024-10-21 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'KADIN'), (2, 'ERKEK')], default=2, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity_number',
            field=models.CharField(default='00000000000', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='TC kimlik numarası 11 rakam olmalıdır.', regex='^\\d{11}$')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=0, max_length=120, verbose_name='Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefon numarası geçerli bir formatta olmalıdır.', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default=0, max_length=120, verbose_name='Soyadı'),
            preserve_default=False,
        ),
    ]
