# Generated by Django 5.1.2 on 2024-10-21 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_gender_customuser_identity_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identity_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='TC kimlik numarası 11 rakam olmalıdır.', regex='^\\d{11}$')]),
        ),
    ]
