# Generated by Django 5.1.2 on 2024-10-21 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identity_number',
            field=models.CharField(default='default_value', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='TC kimlik numarası 11 rakam olmalıdır.', regex='^\\d{11}$')]),
        ),
    ]
