# Generated by Django 5.1.2 on 2024-10-21 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_identity_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identity_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='TC kimlik numarası 11 rakam olmalıdır.', regex='^\\d{11}$')], verbose_name='TC Kimlik Numarası'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefon numarası geçerli bir formatta olmalıdır.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon'),
        ),
    ]
