# Generated by Django 5.1.2 on 2024-10-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_identity_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='district_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
