# Generated by Django 5.1.2 on 2024-10-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_district_id_customuser_district_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='province_name',
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district_id', models.IntegerField(unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='accounts.city')),
            ],
        ),
    ]
