# Generated by Django 5.1.2 on 2024-10-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_city_customuser_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='district_id',
            new_name='id_district',
        ),
    ]
