# Generated by Django 5.1.2 on 2024-10-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='id_district',
            new_name='district_id',
        ),
    ]
