# Generated by Django 5.1.2 on 2024-10-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_city_customuser_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='city', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.CharField(default='district', max_length=100),
        ),
    ]
