# Generated by Django 5.1.2 on 2024-10-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_city_alter_customuser_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='district',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(max_length=250, verbose_name='Adres'),
        ),
    ]
