# Generated by Django 5.1.2 on 2024-10-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='Default Address', max_length=250, verbose_name='Adres'),
        ),
    ]
