# Generated by Django 5.1.2 on 2024-10-23 10:27

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=timezone.now),
            
        ),
    ]
